# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# Workflow para Qualidade de Código, Testes e Cobertura com Python
# Este workflow instalará dependências, executará testes, linting e verificações de qualidade de código.

name: Qualidade de Código e Testes

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  lint_and_test:
    name: Lint, Testar e Verificar Código Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"] # Suporte para várias versões do Python
    steps:
      # Passo 1: Fazer checkout do repositório
      - name: Fazer Checkout do Repositório
        uses: actions/checkout@v4

      # Passo 2: Configurar a versão do Python com base na matriz
      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Passo 3: Instalar dependências do requirements.txt, environment.yml e ferramentas
      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f environment.yml ]; then conda env update --file environment.yml --name base; fi

      # Passo 4: Lintar o código Python com Flake8 para verificações de estilo e complexidade
      - name: Lintar com Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Passo 5: Rodar a análise do Pylint para verificações mais profundas de qualidade de código
      - name: Rodar Análise com Pylint
        run: |
          pylint $(git ls-files '*.py') --fail-under=7 --output-format=json > pylint-relatorio.json

      # Passo 6: Enviar o relatório do Pylint como artefato para revisão
      - name: Enviar Relatório do Pylint
        uses: actions/upload-artifact@v4
        with:
          name: pylint-relatorio
          path: pylint-relatorio.json

      # Passo 7: Rodar os testes com Pytest para verificar as unidades de código
      - name: Testar com Pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Passo 8: Enviar relatórios de cobertura de testes como artefatos para revisão
      - name: Enviar Relatórios de Cobertura de Testes
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-testes
          path: |
            htmlcov/
            coverage.xml

  # Pipeline CI adicional para execução de testes e cobertura
  ci_pipeline:
    name: Pipeline CI - Testes e Cobertura
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Fazer checkout do código
      - name: Fazer Checkout do Código
        uses: actions/checkout@v2

      # Passo 2: Configurar a versão do Python 3.10
      - name: Configurar Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Passo 3: Instalar dependências e configurar ambiente
      - name: Instalar Dependências
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Passo 4: Executar os testes com pytest e gerar relatórios de cobertura
      - name: Executar Testes com Pytest
        run: |
          source .venv/bin/activate
          pytest tests/ --cov=app --cov-report=term --cov-report=html --cov-report=xml -vv

      # Passo 5: Enviar relatórios de cobertura como artefatos
      - name: Enviar Relatórios de Cobertura
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            htmlcov/
            coverage.xml
