name: Python Package using Conda

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      # Checkout do repositório
      - uses: actions/checkout@v4

      # Configuração do Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Adicionando o Conda ao PATH do sistema
      - name: Add conda to system path
        run: echo "$CONDA/bin" >> "$GITHUB_PATH"

      # Instalando as dependências
      - name: Install dependencies
        run: conda env update --file environment.yml --name base

      # Linting com flake8
      - name: Lint with flake8
        run: |
          conda install -y flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Testes com pytest
      - name: Test with pytest
        run: |
          conda install -y pytest
          pytest
