name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Defina a versão do Python que você está usando

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt  # Instalar as dependências, incluindo pytest

    - name: Run tests with pytest
      run: |
        source .venv/bin/activate  # Garantir que o ambiente virtual está ativado
        pytest
