# .github/workflows/test.yml

name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TZ: UTC
      PYTHONPATH: ${{ github.workspace }}

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configuração do Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # 3. Instalação das dependências
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # 4. Execução dos testes com pytest
      - name: Run tests with pytest
        run: |
          source .venv/bin/activate
          pytest tests/ --cov=app --cov-report=term --cov-report=html --cov-report=xml -vv

      # 5. Upload dos relatórios de cobertura
      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            htmlcov/
            coverage.xml
